### ISSUE TITLE
Error Task Segfaults instead of waiting for PS

### ISSUE THREAD

**Issue by andrewmzhang** [jcarreira/cirrus#57]
If the Error Task requests a model after the parameter server has started but before the PS has initialized the model, the error task will segfault.

**Comment by andrewmzhang** [comment]
#58

**Comment by andrewmzhang** [comment]
It seems the error results from the connect in the constructor of PSSparseServerInterface.cpp failing and throwing an error. However this error is then caught by the ErrorTask, but it doesn't quit the program or try to reconnect. When the socket is then used, the Error Task segfaults.

**Comment by jcarreira** [comment]
Should be fixed.
