### ISSUE TITLE
Travis tests sometimes don't pass due to travis slowness

### ISSUE THREAD

**Issue by jcarreira** [jcarreira/cirrus#71]
It seems sometimes the travis tests fail because not enough time is given for the test to converge.

Should we increase the threshold? @andrewmzhang @yangryan0

**Comment by andrewmzhang** [comment]
I think that's a good quick fix.

To fix it more completely maybe we should sum up the total number of updates and compare that to the loss. Although this would require investigating some sort of updates to loss relationships.

**Comment by jcarreira** [comment]
That's too complex. I suggest we relax the threshold.

**Comment by yangryan0** [comment]
Yes I think increasing the threshold should work. I added that small change
to the softmax model PR I added this weekend, since I didn't think I needed
to create another PR for such a small change.

**Comment by jcarreira** [comment]
Ok, that sounds good to me.

**Comment by jcarreira** [comment]
Can we close this?
